# Generated by Django 5.2.5 on 2025-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text='Classe FontAwesome, ex: fas fa-hard-hat', max_length=100)),
                ('description', models.TextField(help_text='Courte description du service')),
                ('details', models.TextField(help_text='Liste des projets, séparés par des sauts de ligne')),
                ('whatsapp_link', models.URLField(help_text='Lien pour commander via WhatsApp')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
