# Generated by Django 5.2.5 on 2025-09-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_is_featured_alter_wishlist_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NaturalBio', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('primary_color', models.CharField(default='#2E7D32', max_length=7)),
                ('accent_color', models.CharField(default='#A5D6A7', max_length=7)),
                ('neutral_light', models.CharField(default='#F1F5F9', max_length=7)),
                ('neutral_dark', models.CharField(default='#0F172A', max_length=7)),
                ('success_color', models.CharField(default='#16A34A', max_length=7)),
                ('warning_color', models.CharField(default='#F59E0B', max_length=7)),
                ('danger_color', models.CharField(default='#DC2626', max_length=7)),
                ('email_primary', models.EmailField(default='contact@naturalbio.com', max_length=254)),
                ('phone_primary', models.CharField(default='+229 123 456 78', max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_banner', models.ImageField(blank=True, null=True, upload_to='site/banners/')),
                ('promo_banner', models.ImageField(blank=True, null=True, upload_to='site/banners/')),
                ('promo_text', models.CharField(blank=True, help_text='Texte affiché dans la barre promo', max_length=255, null=True)),
                ('footer_text', models.TextField(default='© 2025 NaturalBio. Tous droits réservés.')),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
            },
        ),
    ]
